import os
os.system('sudo apt-get update')
os.system('sudo apt upgrade -y')
os.system('sudo apt install nmap')
os.system('sudo git clone https://github.com/scipag/vulscan;sudo mv vulscan /usr/share/nmap/scripts/') # nmap vulners
os.system('sudo apt install wafw00f')
os.system('sudo apt install wget')
os.system('sudo wget https://github.com/projectdiscovery/subfinder/releases/download/v2.6.8/subfinder_2.6.8_linux_amd64.zip; sudo unzip subfinder_2.6.8_linux_amd64.zip; sudo mv subfinder /usr/local/bin')
os.system('sudo apt install pip')
os.system('sudo pip install flask')
os.system('sudo pip install requests')
os.system('sudo install snap')
os.system('sudo snap install httpx')
os.system('sudo apt install chromium-browser')
os.system('sudo apt install apache2')
os.system('sudo apt install unzip')
os.system('sudo wget https://github.com/tomnomnom/waybackurls/releases/download/v0.1.0/waybackurls-linux-amd64-0.1.0.tgz;sudo tar -xvzf waybackurls-linux-amd64-0.1.0.tgz -C /usr/local/bin')
os.system('sudo wget https://github.com/tomnomnom/qsreplace/releases/download/v0.0.3/qsreplace-linux-amd64-0.0.3.tgz;sudo tar -xvzf qsreplace-linux-amd64-0.0.3.tgz -C /usr/local/bin')
os.system('sudo wget https://github.com/tomnomnom/anew/releases/download/v0.1.1/anew-linux-amd64-0.1.1.tgz ;sudo tar -xvzf anew-linux-amd64-0.1.1.tgz -C /usr/local/bin')
os.system('sudo wget https://github.com/projectdiscovery/nuclei/releases/download/v3.3.8/nuclei_3.3.8_linux_amd64.zip; sudo unzip nuclei_3.3.8_linux_amd64.zip; mv nuclei /usr/local/bin')
os.system('sudo pip install --break-system-packages flask-cors')